default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: chat_system_development

test:
  <<: *default
  database: chat_system_test

production:
  <<: *default
  database: chat_system_production
  username: chat_system
  password: <%= ENV['CHAT_SYSTEM_DATABASE_PASSWORD'] %>
